# Generated by Django 4.1 on 2025-01-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=255)),
                ('materials', models.CharField(max_length=255)),
                ('micro_meso_non_porous', models.CharField(choices=[('Micro', 'Micro'), ('Meso', 'Meso'), ('Non Porous', 'Non Porous')], max_length=50)),
                ('estimated_surface_area', models.FloatField()),
                ('degassing_temperature', models.FloatField()),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.reservation')),
            ],
        ),
    ]
